# Generated by Django 5.1.3 on 2024-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='audio_content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='auidio_explaination',
        ),
        migrations.AddField(
            model_name='quiz',
            name='audio_content',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='auidio_explaination',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
