# Generated by Django 5.1.3 on 2024-11-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
