# Generated by Django 5.1.3 on 2024-11-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_contacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
