# Generated by Django 5.1.3 on 2024-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_answer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='correctAnswer',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
