# Generated by Django 5.1.3 on 2024-12-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_quiz_correctanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='recievingMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullNames', models.TextField()),
                ('gmail', models.TextField()),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('seen', models.BooleanField()),
            ],
        ),
    ]
