# Generated by Django 5.1.3 on 2024-12-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_recievingmails'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recievingmails',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
