# Generated by Django 5.1.3 on 2024-12-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_coursecategory_serie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
