# Generated by Django 5.1.3 on 2024-12-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_coursecategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='category',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
