# Generated by Django 5.1.3 on 2024-12-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_coursecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
